packages:
  - apps/**/*
  - packages/**/*

overrides:
  "@mantine/core": "9.7.1"
  "@mantine/hooks": "9.7.1"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@mantine/code-highlight@9.7.1"
  - "@mantine/core@9.7.1"
  - "@mantine/dates@9.7.1"
  - "@mantine/form@9.7.1"
  - "@mantine/hooks@9.7.1"

trustPolicy: no-downgrade
trustPolicyExclude:
  - css-declaration-sorter@6.4.1
  - semver@5.7.2
  - semver@6.3.1
  - undici-types@6.21.0
  - vite@6.4.1
